trigger_pipeline:
  stage: deploy
  script:
    - env
    - 'curl --fail --request POST --form token=$TRIGGER_TOKEN --form ref=refs/tags/$CI_COMMIT_TAG "$TRIGGER_URL"'
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - pdbekb-shell
