trigger_pipeline:
  stage: deploy
  script:
    - 'curl --fail --request POST --form token=$TRIGGER_TOKEN --form ref=$CI_COMMIT_TAG "$TRIGGER_URL"'
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - kb-runner
