trigger_pipeline:
  stage: deploy
  script:
    - 'curl -X POST -F token=$TRIGGER_TOKEN -F ref=master -F tagname=$CI_COMMIT_TAG "$TRIGGER_URL"'
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - pdbekb-shell
