version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000
    environment:
      - ENVIRONMENT=DEV
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/1
      - MAX_POST_LIMIT=10
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - worker

  worker:
    build: .
    command: celery -A worker.worker worker -l info -n worker.worker
    volumes:
      - ./worker:/worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MAX_POST_LIMIT=5
      - BEACONS_API_URL=http://web:8000
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  dashboard:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

volumes:
  redis_data:
