# generated by datamodel-codegen:
#   filename:  3dbeacons.yaml
#   timestamp: 2022-05-13T10:29:41+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class StrictBaseModel(BaseModel):
    model_config = {"extra": "ignore"}


class UniprotEntry(StrictBaseModel):
    ac: str = Field(
        ..., description="UniProt accession", json_schema_extra={"example": "P00520"}
    )
    id: Optional[str] = Field(
        None,
        description="UniProt identifier",
        json_schema_extra={"example": "ABL1_MOUSE"},
    )
    uniprot_checksum: Optional[str] = Field(
        None,
        description="CRC64 checksum of the UniProt sequence",
        json_schema_extra={"example": "5F9BA1D4C7DE6925"},
    )
    sequence_length: Optional[int] = Field(
        None,
        description="Length of the UniProt sequence",
        json_schema_extra={"example": 76},
    )
    segment_start: Optional[int] = Field(
        None,
        description="1-indexed first residue of the UniProt sequence segment",
        json_schema_extra={"example": 1},
    )
    segment_end: Optional[int] = Field(
        None,
        description="1-indexed last residue of the UniProt sequence segment",
        json_schema_extra={"example": 86},
    )
    description: Optional[str] = Field(
        None,
        description="Description of the UniProt entry",
        json_schema_extra={"example": "Proto-oncogene tyrosine-protein kinase ABL1"},
    )


class PdbEntry(StrictBaseModel):
    entry_id: str = Field(
        ..., description="PDB entry identifier", json_schema_extra={"example": "3bow"}
    )
    chain_id: str = Field(
        ..., description="PDB chain identifier", json_schema_extra={"example": "A"}
    )
    mapped_uniprot: Optional[str] = Field(
        None,
        description="UniProt accession mapped to the PDB entry",
        json_schema_extra={"example": "P12345"},
    )
    uniprot_start: int = Field(
        ...,
        description="1-indexed first residue in the mapped UniProt",
        json_schema_extra={"example": 1},
    )
    uniprot_end: int = Field(
        ...,
        description="1-indexed last residue in the mapped UniProt",
        json_schema_extra={"example": 100},
    )


class ModelCategory(Enum):
    EXPERIMENTALLY_DETERMINED = "EXPERIMENTALLY DETERMINED"
    TEMPLATE_BASED = "TEMPLATE-BASED"
    AB_INITIO = "AB-INITIO"
    CONFORMATIONAL_ENSEMBLE = "CONFORMATIONAL ENSEMBLE"


class ModelFormat(Enum):
    PDB = "PDB"
    MMCIF = "MMCIF"
    BCIF = "BCIF"


class ModelType(Enum):
    ATOMIC = "ATOMIC"
    DUMMY = "DUMMY"
    MIX = "MIX"


class EnsembleSampleFormat(Enum):
    PDB = "PDB"
    MMCIF = "MMCIF"
    BCIF = "BCIF"


class ExperimentalMethod(Enum):
    ELECTRON_CRYSTALLOGRAPHY = "ELECTRON CRYSTALLOGRAPHY"
    ELECTRON_MICROSCOPY = "ELECTRON MICROSCOPY"
    EPR = "EPR"
    FIBER_DIFFRACTION = "FIBER DIFFRACTION"
    FLUORESCENCE_TRANSFER = "FLUORESCENCE TRANSFER"
    INFRARED_SPECTROSCOPY = "INFRARED SPECTROSCOPY"
    NEUTRON_DIFFRACTION = "NEUTRON DIFFRACTION"
    X_RAY_POWDER_DIFFRACTION = "X-RAY POWDER DIFFRACTION"
    SOLID_STATE_NMR = "SOLID-STATE NMR"
    SOLUTION_NMR = "SOLUTION NMR"
    X_RAY_SOLUTION_SCATTERING = "X-RAY SOLUTION SCATTERING"
    THEORETICAL_MODEL = "THEORETICAL MODEL"
    X_RAY_DIFFRACTION = "X-RAY DIFFRACTION"
    HYBRID = "HYBRID"


class ConfidenceType(Enum):
    pLDDT = "pLDDT"
    QMEANDisCo = "QMEANDisCo"
    ipTMPlusPTM = "ipTM+pTM"


class OligomericState(Enum):
    MONOMER = "MONOMER"
    HOMODIMER = "HOMODIMER"
    HETERODIMER = "HETERODIMER"
    HOMO_OLIGOMER = "HOMO-OLIGOMER"
    HETERO_OLIGOMER = "HETERO-OLIGOMER"


class EntityType(Enum):
    BRANCHED = "BRANCHED"
    MACROLIDE = "MACROLIDE"
    NON_POLYMER = "NON-POLYMER"
    POLYMER = "POLYMER"
    WATER = "WATER"


class EntityPolyType(Enum):
    CYCLIC_PSEUDO_PEPTIDE = "CYCLIC-PSEUDO-PEPTIDE"
    PEPTIDE_NUCLEIC_ACID = "PEPTIDE NUCLEIC ACID"
    POLYDEOXYRIBONUCLEOTIDE = "POLYDEOXYRIBONUCLEOTIDE"
    POLYDEOXYRIBONUCLEOTIDE_POLYRIBONUCLEOTIDE_HYBRID = (
        "POLYDEOXYRIBONUCLEOTIDE/POLYRIBONUCLEOTIDE HYBRID"
    )
    POLYPEPTIDE_D_ = "POLYPEPTIDE(D)"
    POLYPEPTIDE_L_ = "POLYPEPTIDE(L)"
    POLYRIBONUCLEOTIDE = "POLYRIBONUCLEOTIDE"
    OTHER = "OTHER"


class IdentifierCategory(Enum):
    UNIPROT = "UNIPROT"
    RFAM = "RFAM"
    CCD = "CCD"
    SMILES = "SMILES"
    INCHI = "INCHI"
    INCHIKEY = "INCHIKEY"


class Entity(StrictBaseModel):
    entity_type: EntityType = Field(
        ...,
        description="The type of the molecular entity; similar to _entity.type in"
        " mmCIF",
        json_schema_extra={"example": "POLYMER"},
    )
    entity_poly_type: Optional[EntityPolyType] = Field(
        None,
        description="The type of the molecular entity; similar to _entity_poly.type"
        " in mmCIF",
        json_schema_extra={"example": "PEPTIDE NUCLEIC ACID"},
    )
    identifier: Optional[str] = Field(
        None,
        description="Identifier of the molecule",
        json_schema_extra={"example": "Q13033"},
    )
    identifier_category: Optional[IdentifierCategory] = Field(
        None,
        description="Category of the identifier",
        json_schema_extra={"example": "UNIPROT"},
    )
    description: str = Field(
        ...,
        description="A textual label of the molecule",
        json_schema_extra={"example": "Striatin-3"},
    )
    chain_ids: List[str] = Field(
        ...,
        description="A list of label_asym identifiers "
        "( chain_id in the case of PDB format) of the molecule",
        json_schema_extra={"example": ["A", "B"]},
    )


class SummaryItems(StrictBaseModel):
    model_identifier: str = Field(
        ...,
        description="Identifier of the model, such as PDB id",
        json_schema_extra={"example": "8kfa"},
    )
    model_category: ModelCategory = Field(
        ...,
        description="Category of the model",
        json_schema_extra={"example": "TEMPLATE-BASED"},
    )
    model_url: str = Field(
        ...,
        description="URL of the model coordinates",
        json_schema_extra={
            "example": "https://www.ebi.ac.uk/pdbe/static/entry/1t29_updated.cif"
        },
    )
    model_format: ModelFormat = Field(
        ...,
        description="File format of the coordinates",
        json_schema_extra={"example": "MMCIF"},
    )
    model_type: Optional[ModelType] = Field(
        None,
        description="Defines if the coordinates are atomic-level or contains "
        "dummy atoms (e.g. SAXS models), or a mix of both (e.g. hybrid models)\n",
        json_schema_extra={"example": "ATOMIC"},
    )
    model_page_url: Optional[str] = Field(
        None,
        description="URL of a web page of the data provider that show the model",
        json_schema_extra={"example": "https://alphafold.ebi.ac.uk/entry/Q5VSL9"},
    )
    provider: str = Field(
        ...,
        description="Name of the model provider",
        json_schema_extra={"example": "SWISS-MODEL"},
    )
    number_of_conformers: Optional[float] = Field(
        None,
        description="The number of conformers in a conformational ensemble",
        json_schema_extra={"example": 42},
    )
    ensemble_sample_url: Optional[str] = Field(
        None,
        description="URL of a sample of conformations from a conformational "
        "ensemble",
        json_schema_extra={
            "example": "https://proteinensemble.org/api/ensemble_sample/PED00001e001"
        },
    )
    ensemble_sample_format: Optional[EnsembleSampleFormat] = Field(
        None,
        description="File format of the sample coordinates, e.g. PDB",
        json_schema_extra={"example": "PDB"},
    )
    created: str = Field(
        ...,
        description="Date of release of model generation in the format of YYYY-MM-DD",
        json_schema_extra={"example": "2021-12-21"},
    )
    sequence_identity: float = Field(
        ...,
        description="Sequence identity in the range of [0,1] of the model to the "
        "UniProt sequence\n",
        json_schema_extra={"example": 0.97},
    )
    uniprot_start: int = Field(
        ...,
        description="1-indexed first residue of the model according to UniProt "
        "sequence numbering\n",
        json_schema_extra={"example": 1},
    )
    uniprot_end: int = Field(
        ...,
        description="1-indexed last residue of the model according to UniProt "
        "sequence numbering\n",
        json_schema_extra={"example": 142},
    )
    coverage: float = Field(
        ...,
        description="Fraction in range of [0, 1] of the UniProt sequence covered by "
        "the model.  This is calculated as (uniprot_end - uniprot_start + 1) / "
        "uniprot_sequence_length\n",
        json_schema_extra={"example": 0.4},
    )
    experimental_method: Optional[ExperimentalMethod] = Field(
        None,
        description="Experimental method used to determine the structure, if "
        "applicable",
    )
    resolution: Optional[float] = Field(
        None,
        description="The resolution of the model in Angstrom, if applicable",
        json_schema_extra={"example": 1.4},
    )
    confidence_type: Optional[ConfidenceType] = Field(
        None,
        description="Type of the confidence measure. This is required for  "
        "theoretical models.\n",
        json_schema_extra={"example": "QMEANDisCo"},
    )
    confidence_version: Optional[str] = Field(
        None,
        description="Version of confidence measure software used to calculate quality. "
        "This is required for theoretical models.\n",
        json_schema_extra={"example": "v1.0.2"},
    )
    confidence_avg_local_score: Optional[float] = Field(
        None,
        description="Average of the confidence measures in the range of [0,1] for "
        "QMEANDisCo  and [0,100] for pLDDT. Please contact 3D-Beacons developers "
        "if other  estimates are to be added. This is required for theoretical "
        "models.\n",
        json_schema_extra={"example": 0.95},
    )
    oligomeric_state: Optional[OligomericState] = Field(
        None,
        description="Oligomeric state of the model",
        json_schema_extra={"example": "MONOMER"},
    )
    oligomeric_state_confidence: Optional[float] = Field(
        None,
        description="Numerical value that describes the confidence in the oligomeric "
        "state of the predicted complex",
        json_schema_extra={"example": 0.4603},
    )
    preferred_assembly_id: Optional[str] = Field(
        None,
        description="Identifier of the preferred assembly in the model",
        json_schema_extra={"example": "1A"},
    )
    entities: List[Entity] = Field(
        ..., description="A list of molecular entities in the model"
    )


class ExperimentalMethod1(Enum):
    ELECTRON_CRYSTALLOGRAPHY = "ELECTRON CRYSTALLOGRAPHY"
    ELECTRON_MICROSCOPY = "ELECTRON MICROSCOPY"
    EPR = "EPR"
    FIBER_DIFFRACTION = "FIBER DIFFRACTION"
    FLUORESCENCE_TRANSFER = "FLUORESCENCE TRANSFER"
    INFRARED_SPECTROSCOPY = "INFRARED SPECTROSCOPY"
    NEUTRON_DIFFRACTION = "NEUTRON DIFFRACTION"
    POWDER_DIFFRACTION = "POWDER DIFFRACTION"
    SOLID_STATE_NMR = "SOLID-STATE NMR"
    SOLUTION_NMR = "SOLUTION NMR"
    SOLUTION_SCATTERING = "SOLUTION SCATTERING"
    THEORETICAL_MODEL = "THEORETICAL MODEL"
    X_RAY_DIFFRACTION = "X-RAY DIFFRACTION"
    HYBRID = "HYBRID"


class Template(StrictBaseModel):
    template_id: str = Field(
        ...,
        description="Identifier of the template",
        json_schema_extra={"example": "2aqa"},
    )
    chain_id: str = Field(
        ...,
        description="Identifier of the chain of the template; this is label_asym_id in "
        "mmCIF",
        json_schema_extra={"example": "C"},
    )
    template_sequence_identity: float = Field(
        ...,
        description="Sequence identity of the template with the  UniProt accession, "
        "in the range of [0,1]\n",
        json_schema_extra={"example": 0.97},
    )
    last_updated: str = Field(
        ...,
        description="Date of release of the last update in  the format of YYYY-MM-DD\n",
        json_schema_extra={"example": "2021-08-06"},
    )
    provider: str = Field(
        ...,
        description="Provider of the template",
        json_schema_extra={"example": "PDB"},
    )
    experimental_method: ExperimentalMethod1 = Field(
        ...,
        description="Experimental method used to determine the template",
        json_schema_extra={"example": "HYBRID"},
    )
    resolution: float = Field(
        ...,
        description="Resolution of the template, in Angstrom",
        json_schema_extra={"example": 2.1},
    )
    preferred_assembly_id: Optional[str] = Field(
        None,
        description="Identifier of the preferred assembly of the template",
        json_schema_extra={"example": "1"},
    )


class Seqres(StrictBaseModel):
    aligned_sequence: str = Field(
        ...,
        description="Sequence of the model",
        json_schema_extra={"example": "AAGTGHLKKKYT..."},
    )
    from_: int = Field(
        ...,
        alias="from",
        description="1-indexed first residue",
        json_schema_extra={"example": 32},
    )
    to: int = Field(
        ..., description="1-indexed last residue", json_schema_extra={"example": 976}
    )


class Uniprot(StrictBaseModel):
    aligned_sequence: str = Field(
        ...,
        description="Sequence of the UniProt accession",
        json_schema_extra={"example": "AAGTGHLKKKYTAAGTGHLKKKYT..."},
    )
    from_: int = Field(
        ...,
        alias="from",
        description="1-indexed first residue",
        json_schema_extra={"example": 23},
    )
    to: int = Field(
        ..., description="1-indexed last residue", json_schema_extra={"example": 868}
    )


class Residue(StrictBaseModel):
    confidence: Optional[float] = Field(
        None,
        description="Confidence score in the range of [0,1]",
        json_schema_extra={"example": 0.99},
    )
    model_residue_label: int = Field(
        ..., description="Model residue index", json_schema_extra={"example": 1}
    )
    uniprot_residue_number: int = Field(
        ..., description="UniProt residue index", json_schema_extra={"example": 1}
    )


class Segment(StrictBaseModel):
    templates: Optional[List[Template]] = Field(
        None, description="Information on the template(s) used for the model"
    )
    seqres: Seqres = Field(..., description="Information on the sequence of the model")
    uniprot: Uniprot
    residues: List[Residue]


class Chain(StrictBaseModel):
    chain_id: str
    segments: Optional[List[Segment]] = None


class Chains(RootModel[List[Chain]]):
    model_config = {"title": "Chains"}


class LigandItem(StrictBaseModel):
    id: str = Field(
        ...,
        description="Three-letter code of the ligand",
        json_schema_extra={"example": "IHP"},
    )
    name: str = Field(
        ...,
        description="Name of the small ligand",
        json_schema_extra={"example": "INOSITOL HEXAKISPHOSPHATE"},
    )
    formula: str = Field(
        ...,
        description="Chemical composition formula of the ligand",
        json_schema_extra={"example": "C6 H18 O24 P6"},
    )
    inchikey: str = Field(
        ...,
        description="InChIKey of the ligand",
        json_schema_extra={"example": "IMQLKJBTEOYOSI-GPIVLXJGSA-N"},
    )


class Type(Enum):
    HELIX = "HELIX"
    SHEET = "SHEET"
    COIL = "COIL"


class RegionItem(StrictBaseModel):
    start: int = Field(
        ...,
        description="The first position of the annotation",
        json_schema_extra={"example": 23},
    )
    end: int = Field(
        ...,
        description="The last position of the annotation",
        json_schema_extra={"example": 42},
    )


class SecondaryStructureItem(StrictBaseModel):
    type: Type = Field(
        ...,
        description="Type of the secondary structure element",
        json_schema_extra={"example": "HELIX"},
    )
    region: Optional[List[RegionItem]] = None


class Type1(Enum):
    CARBOHYD = "CARBOHYD"
    DOMAIN = "DOMAIN"
    CA_BIND = "CA_BIND"
    DNA_BIND = "DNA_BIND"
    NP_BIND = "NP_BIND"
    ACT_SITE = "ACT_SITE"
    METAL = "METAL"
    BINDING = "BINDING"
    NON_STD = "NON_STD"
    MOD_RES = "MOD_RES"
    DISULFID = "DISULFID"
    MUTAGEN = "MUTAGEN"


class Region(StrictBaseModel):
    start: int = Field(
        ...,
        description="The first position of the annotation",
        json_schema_extra={"example": 23},
    )
    end: int = Field(
        ...,
        description="The last position of the annotation",
        json_schema_extra={"example": 42},
    )


class FeatureItem(StrictBaseModel):
    type: Type1 = Field(
        ...,
        description="Type of the annotation",
        json_schema_extra={"example": "ACT_SITE"},
    )
    description: str = Field(
        ...,
        description="Description/Label of the annotation",
        json_schema_extra={"example": "Pfam N1221 (PF07923)"},
    )
    residues: Optional[List[int]] = Field(
        None, description="An array of residue indices"
    )
    regions: Optional[List[Region]] = None


class Annotations(StrictBaseModel):
    accession: str = Field(
        ..., description="A UniProt accession", json_schema_extra={"example": "P00734"}
    )
    id: Optional[str] = Field(
        None,
        description="A UniProt identifier",
        json_schema_extra={"example": "FGFR2_HUMAN"},
    )
    sequence: str = Field(
        ...,
        description="The sequence of the protein",
        json_schema_extra={"example": "AFFGVAATRKL"},
    )
    ligand: Optional[List[LigandItem]] = Field(
        None, description="Contains ligand annotations"
    )
    secondary_structure: Optional[List[SecondaryStructureItem]] = None
    feature: Optional[List[FeatureItem]] = None


class MappingAccessionType(Enum):
    uniprot = "uniprot"
    pfam = "pfam"


class ModelCategory1(Enum):
    EXPERIMENTALLY_DETERMINED = "EXPERIMENTALLY DETERMINED"
    TEMPLATE_BASED = "TEMPLATE-BASED"
    AB_INITIO = "AB-INITIO"
    CONFORMATIONAL_ENSEMBLE = "CONFORMATIONAL ENSEMBLE"
    DEEP_LEARNING = "DEEP-LEARNING"


class ModelType1(Enum):
    single = "single"
    complex = "complex"


class Metadata(StrictBaseModel):
    mappingAccession: str = Field(
        ...,
        description="Accession/identifier of the entity the model is mapped to",
        json_schema_extra={"example": "P38398"},
    )
    mappingAccessionType: MappingAccessionType = Field(
        ...,
        description="The name of the data provider the model is mapped to",
        json_schema_extra={"example": "uniprot"},
    )
    start: int = Field(
        ...,
        description="The index of the first residue of the model according to the "
        "mapping",
        json_schema_extra={"example": 1},
    )
    end: int = Field(
        ...,
        description="The index of the last residue of the model according to the "
        "mapping",
        json_schema_extra={"example": 103},
    )
    modelCategory: ModelCategory1 = Field(
        ...,
        description="Category of the model",
        json_schema_extra={"example": "TEMPLATE-BASED"},
    )
    modelType: ModelType1 = Field(
        ...,
        description="Monomeric or complex strutures",
        json_schema_extra={"example": "single"},
    )


class Detailed(StrictBaseModel):
    summary: SummaryItems
    chains: Chains


class Overview(StrictBaseModel):
    summary: SummaryItems


class UniprotSummary(StrictBaseModel):
    uniprot_entry: Optional[UniprotEntry] = None
    structures: Optional[List[Overview]] = None


class UniprotDetails(StrictBaseModel):
    uniprot_entry: Optional[UniprotEntry] = None
    structures: Optional[List[Detailed]] = None


class PdbSummary(StrictBaseModel):
    uniprot_entry: Optional[PdbEntry] = None
    structures: Optional[List[Overview]] = None


class AccessionListRequest(StrictBaseModel):
    accessions: List[str] = Field(
        ...,
        description="A list of UniProt accessions",
        json_schema_extra={"example": ["P00734", "P38398"]},
    )
    provider: Optional[str] = Field(
        None,
        description="Name of the model provider",
        json_schema_extra={"example": "swissmodel"},
    )
    exclude_provider: Optional[str] = Field(
        None, description="Provider to exclude.", json_schema_extra={"example": "pdbe"}
    )
