# generated by datamodel-codegen:
#   filename:  3dbeacons.yaml
#   timestamp: 2022-05-13T10:29:41+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from app.uniprot.schema import UniprotSummary


class EnsemblTranscript(BaseModel):
    transcript_id: str = Field(..., description="Transcript identifier")
    seqRegionStart: int = Field(..., description="Start position of the transcript")
    seqRegionEnd: int = Field(..., description="End position of the transcript")
    alignment_difference: Optional[float] = Field(
        None, description="Fraction of alignment difference (0 to 1)", ge=0, le=1
    )


class UniprotMapping(BaseModel):
    ensembl_transcript: EnsemblTranscript
    uniprot_accession: UniprotSummary


class EnsemblSummary(BaseModel):
    ensembl_id: str = Field(..., description="An Ensembl identifier")
    species: str = Field(..., description="Species name")
    taxid: str = Field(..., description="Taxonomy identifier")
    uniprot_mappings: List[UniprotMapping]
